{
  "fetched_at": "2026-04-09T02:10:15.179961+00:00",
  "source": "Akron / Summit County, Ohio",
  "date_range": {
    "from": "2026-01-09",
    "to": "2026-04-09"
  },
  "total": 12,
  "with_address": 0,
  "records": [
    {
      "doc_num": "Civil Protection Orders",
      "doc_type": "PRO",
      "filed": "2026-04-09",
      "cat": "PRO",
      "cat_label": "Probate / Estate",
      "owner": "",
      "grantee": "",
      "amount": null,
      "legal": "",
      "prop_address": "",
      "prop_city": "",
      "prop_state": "OH",
      "prop_zip": "",
      "mail_address": "",
      "mail_city": "",
      "mail_state": "",
      "mail_zip": "",
      "clerk_url": "https://clerkweb.summitoh.net/civil-protection-orders",
      "flags": [
        "Probate / estate",
        "New this week"
      ],
      "score": 55
    },
    {
      "doc_num": "PRO-1",
      "doc_type": "PRO",
      "filed": "2026-04-09",
      "cat": "PRO",
      "cat_label": "Probate / Estate",
      "owner": "Skip to main content",
      "grantee": "",
      "amount": null,
      "legal": "",
      "prop_address": "",
      "prop_city": "",
      "prop_state": "OH",
      "prop_zip": "",
      "mail_address": "",
      "mail_city": "",
      "mail_state": "",
      "mail_zip": "",
      "clerk_url": "https://search.summitohioprobate.com/eservices/#mainContent",
      "flags": [
        "Probate / estate",
        "New this week"
      ],
      "score": 55
    },
    {
      "doc_num": "PRO-2",
      "doc_type": "PRO",
      "filed": "2026-04-09",
      "cat": "PRO",
      "cat_label": "Probate / Estate",
      "owner": "Home currently selected",
      "grantee": "",
      "amount": null,
      "legal": "",
      "prop_address": "",
      "prop_city": "",
      "prop_state": "OH",
      "prop_zip": "",
      "mail_address": "",
      "mail_city": "",
      "mail_state": "",
      "mail_zip": "",
      "clerk_url": "https://search.summitohioprobate.com/eservices/home.page",
      "flags": [
        "Probate / estate",
        "New this week"
      ],
      "score": 55
    },
    {
      "doc_num": "PRO-3",
      "doc_type": "PRO",
      "filed": "2026-04-09",
      "cat": "PRO",
      "cat_label": "Probate / Estate",
      "owner": "Click Here",
      "grantee": "",
      "amount": null,
      "legal": "",
      "prop_address": "",
      "prop_city": "",
      "prop_state": "OH",
      "prop_zip": "",
      "mail_address": "",
      "mail_city": "",
      "mail_state": "",
      "mail_zip": "",
      "clerk_url": "https://search.summitohioprobate.com/eservices/",
      "flags": [
        "Probate / estate",
        "New this week"
      ],
      "score": 55
    },
    {
      "doc_num": "PRO-4",
      "doc_type": "PRO",
      "filed": "2026-04-09",
      "cat": "PRO",
      "cat_label": "Probate / Estate",
      "owner": "Summit County Clerk of Courts",
      "grantee": "",
      "amount": null,
      "legal": "",
      "prop_address": "",
      "prop_city": "",
      "prop_state": "OH",
      "prop_zip": "",
      "mail_address": "",
      "mail_city": "",
      "mail_state": "",
      "mail_zip": "",
      "clerk_url": "https://clerkweb.summitoh.net/",
      "flags": [
        "Probate / estate",
        "New this week"
      ],
      "score": 55
    },
    {
      "doc_num": "PRO-5",
      "doc_type": "PRO",
      "filed": "2026-04-09",
      "cat": "PRO",
      "cat_label": "Probate / Estate",
      "owner": "Summit County Common Pleas Court",
      "grantee": "",
      "amount": null,
      "legal": "",
      "prop_address": "",
      "prop_city": "",
      "prop_state": "OH",
      "prop_zip": "",
      "mail_address": "",
      "mail_city": "",
      "mail_state": "",
      "mail_zip": "",
      "clerk_url": "http://www.summitcpcourt.net/",
      "flags": [
        "Probate / estate",
        "New this week"
      ],
      "score": 55
    },
    {
      "doc_num": "PRO-6",
      "doc_type": "PRO",
      "filed": "2026-04-09",
      "cat": "PRO",
      "cat_label": "Probate / Estate",
      "owner": "Summit County Domestic Relations Court",
      "grantee": "",
      "amount": null,
      "legal": "",
      "prop_address": "",
      "prop_city": "",
      "prop_state": "OH",
      "prop_zip": "",
      "mail_address": "",
      "mail_city": "",
      "mail_state": "",
      "mail_zip": "",
      "clerk_url": "http://www.drcourt.org/",
      "flags": [
        "Probate / estate",
        "New this week"
      ],
      "score": 55
    },
    {
      "doc_num": "PRO-7",
      "doc_type": "PRO",
      "filed": "2026-04-09",
      "cat": "PRO",
      "cat_label": "Probate / Estate",
      "owner": "The County of Summit",
      "grantee": "",
      "amount": null,
      "legal": "",
      "prop_address": "",
      "prop_city": "",
      "prop_state": "OH",
      "prop_zip": "",
      "mail_address": "",
      "mail_city": "",
      "mail_state": "",
      "mail_zip": "",
      "clerk_url": "https://co.summitoh.net/",
      "flags": [
        "Probate / estate",
        "New this week"
      ],
      "score": 55
    },
    {
      "doc_num": "PRO-8",
      "doc_type": "PRO",
      "filed": "2026-04-09",
      "cat": "PRO",
      "cat_label": "Probate / Estate",
      "owner": "Ohio Department of Taxation",
      "grantee": "",
      "amount": null,
      "legal": "",
      "prop_address": "",
      "prop_city": "",
      "prop_state": "OH",
      "prop_zip": "",
      "mail_address": "",
      "mail_city": "",
      "mail_state": "",
      "mail_zip": "",
      "clerk_url": "http://www.tax.ohio.gov/",
      "flags": [
        "Probate / estate",
        "New this week"
      ],
      "score": 55
    },
    {
      "doc_num": "PRO-9",
      "doc_type": "PRO",
      "filed": "2026-04-09",
      "cat": "PRO",
      "cat_label": "Probate / Estate",
      "owner": "Ohio Supreme Court",
      "grantee": "",
      "amount": null,
      "legal": "",
      "prop_address": "",
      "prop_city": "",
      "prop_state": "OH",
      "prop_zip": "",
      "mail_address": "",
      "mail_city": "",
      "mail_state": "",
      "mail_zip": "",
      "clerk_url": "http://www.sconet.state.oh.us/",
      "flags": [
        "Probate / estate",
        "New this week"
      ],
      "score": 55
    },
    {
      "doc_num": "PRO-10",
      "doc_type": "PRO",
      "filed": "2026-04-09",
      "cat": "PRO",
      "cat_label": "Probate / Estate",
      "owner": "eMarriage - Online Marriage Application",
      "grantee": "",
      "amount": null,
      "legal": "",
      "prop_address": "",
      "prop_city": "",
      "prop_state": "OH",
      "prop_zip": "",
      "mail_address": "",
      "mail_city": "",
      "mail_state": "",
      "mail_zip": "",
      "clerk_url": "https://summitohioprobate.com/emarriage-application",
      "flags": [
        "Probate / estate",
        "New this week"
      ],
      "score": 55
    },
    {
      "doc_num": "PRO-11",
      "doc_type": "PRO",
      "filed": "2026-04-09",
      "cat": "PRO",
      "cat_label": "Probate / Estate",
      "owner": "WCAG Compliance",
      "grantee": "",
      "amount": null,
      "legal": "",
      "prop_address": "",
      "prop_city": "",
      "prop_state": "OH",
      "prop_zip": "",
      "mail_address": "",
      "mail_city": "",
      "mail_state": "",
      "mail_zip": "",
      "clerk_url": "https://search.summitohioprobate.com/eservices/accessibility.page",
      "flags": [
        "Probate / estate",
        "New this week"
      ],
      "score": 55
    }
  ]
}
