#!/usr/bin/env python
"""Weekday county-data refresh orchestrator for the Akron dashboard.

Regenerates the enabled counties' dashboard data from their REAL local
sources, writes a refresh log, and updates each county's data only on a
successful real refresh. Designed to be run by Windows Task Scheduler at
06:00, Monday–Friday (see tools/REFRESH.md).

Honesty rules (match the dashboard's no-fake-data policy):
  - Skips disabled counties (e.g. Clark) — never enables or fabricates them.
  - Skips a county honestly when its real source file is missing (status
    "skipped_source_missing") instead of writing stale/empty data.
  - Summit / Cuyahoga are produced by their own existing scraper pipeline
    (not owned by this repo's adapter); they are reported as "external" and
    left untouched here.
  - The refresh timestamp written into a county payload is the real dataset
    date, never "today" unless the data was genuinely pulled today.

Exit code 0 always (a missing optional source is not a failure); per-county
status is in dashboard/refresh_log.json.
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path

import factory_csv_to_records as adapter

REPO = Path(__file__).resolve().parents[1]

# Montgomery is generated by THIS repo's adapter from county-data-factory
# local outputs. Paths are the operator's real local files; override via env.
FACTORY = Path(os.environ.get(
    "FACTORY_REPO", r"C:\Users\nodaysoff\county-data-factory"))
DOWNLOADS = Path(os.environ.get(
    "DOWNLOADS_DIR", r"C:\Users\nodaysoff\Downloads"))


def _latest(glob_dir: Path, pattern: str):
    """Newest file matching pattern (by name, which carries the date), or None."""
    if not glob_dir.is_dir():
        return None
    hits = sorted(glob_dir.glob(pattern))
    return hits[-1] if hits else None


def _dataset_date_from_name(p: Path) -> str:
    """Pull a YYYY-MM-DD out of a filename like leads_montgomery_oh_2026-06-04.csv."""
    import re
    m = re.search(r"(\d{4}-\d{2}-\d{2})", p.name)
    return m.group(1) if m else ""


def refresh_montgomery() -> dict:
    csv_path = _latest(DOWNLOADS, "leads_montgomery_oh_*.csv")
    auditor = FACTORY / "data" / "raw" / "montgomery_auditor_iasworld.jsonl"
    if not csv_path or not csv_path.is_file():
        return {"status": "skipped_source_missing",
                "needed": "imports/montgomery_oh/leads or Downloads/leads_montgomery_oh_*.csv"}
    fetched_at = _dataset_date_from_name(csv_path)
    import csv as _csv
    with open(csv_path, encoding="utf-8-sig", newline="") as f:
        rows = list(_csv.DictReader(f))
    aud = adapter.load_auditor(str(auditor)) if auditor.is_file() else {}
    payload = adapter.build(rows, "Montgomery County", "montgomery", "Dayton Metro",
                            "https://www.mcohio.org/1521/Delinquent-List", fetched_at, aud)
    out = REPO / "dashboard" / "montgomery" / "records.json"
    out.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return {"status": "refreshed", "source": csv_path.name, "dataset_date": fetched_at,
            "records": payload["record_count"], "auditor_facts": bool(aud)}


# counties whose data this repo's adapter owns; others are external pipelines.
ADAPTER_OWNED = {"montgomery": refresh_montgomery}


def main() -> int:
    ran_at = datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")
    counties = json.loads((REPO / "dashboard" / "counties.json").read_text(encoding="utf-8"))
    report = {}
    for key, cfg in counties.items():
        if cfg.get("enabled") is False:
            report[key] = {"status": "skipped_disabled"}
            continue
        if key in ADAPTER_OWNED:
            try:
                report[key] = ADAPTER_OWNED[key]()
            except Exception as e:  # never let one county break the run
                report[key] = {"status": "error", "error": str(e)}
        else:
            report[key] = {"status": "external_pipeline",
                           "note": "produced by its own scraper workflow; not refreshed here"}
    log = {"ran_at": ran_at, "counties": report}
    (REPO / "dashboard" / "refresh_log.json").write_text(
        json.dumps(log, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(log, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
